[package]
name = "m07-tower-hanoi"
version = "0.1.0"
edition = "2021"
authors = ["Eder Andrés Ávila Niño"]

[[bin]]
name = "m07-tower-hanoi"
path ="src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
