[package]
name = "m02-fibonacci"
version = "0.1.0"
edition = "2021"
authors = ["Eder Andrés Ávila Niño"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
